import = [
  "~/.config/alacritty/themes/themes/themes/tokyo-night-storm.",
  "~/.config/alacritty/keybindings.toml",

]
[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new -s 'main'"]

[font]
size = 14.5

[font.bold]
family = "VictorMono Nerd Font"
style = "SemiBold Oblique"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Thin Oblique"

[font.normal]
family = "VictorMono Nerd Font"
style = "Medium"


[scrolling]
history = 100000

[window]
decorations = "Buttonless" 

