#!/bin/zsh
#
# .aliases - Set whatever shell aliases you want.
alias lsh='glow /Users/y/vaults/work/1726059295-ZDFE.md'
alias surh='glow /Users/y/vaults/work/1726064037-FFNH.md'
alias yyh='glow /Users/y/vaults/work/1726064037-FFNH.md'
alias yazih='glow /Users/y/vaults/work/1726065826-OJGB.md'

# single character aliases - be sparing!
alias l=ls
alias g=git

# find
alias fd='find . -type d -name'
alias ff='find . -type f -name'


# misc
alias zshrc='${EDITOR:-vim} "${ZDOTDIR:-$HOME}"/.zshrc'
alias zdot='cd ${ZDOTDIR:-~}'
