[default_session]
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Home 󱂵 "
path = "~/"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Notes  "
path = "~/Vaults/2025/"
preview_command = "eza --all --git --icons --color=always {}"
startup_command = "nvim $(date +%m)"

[[session]]
name = "Downloads  "
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "ovet admin  "
path = "~/Repos/ovet-admin/"
preview_command = "bat --color=always ~/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "Repos 󰊢 "
path = "~/Repos/"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "tmux "
path = "~/dotfiles/.config/tmux"
preview_command = "bat --color=always ~/dotfiles/.config/tmux/tmux.conf"
startup_command = "nvim tmux.conf"

[[sesh]]
name = "sesh "
path = "~/dotfiles/.config/sesh"
preview_command = "bat --color=always ~/dotfiles/.config/tmux/tmux.conf"
startup_command = "nvim sesh.toml"
