[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]
[font]
size = 13.5

[scrolling]
history = 50000
multiplier = 3


[font.bold]
family = "JetbrainsMono Nerd Font"
style = "SemiBold Oblique"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
# family = "VictorMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
# family = "VictorMono Nerd Font"
style = "Thin Oblique"

[font.normal]
family = "JetbrainsMono Nerd Font"
# family = "VictorMono Nerd Font"
style = "Medium"


[window]
decorations = "Buttonless"
blur = true
option_as_alt = "Both"
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.93

